import { render, screen, fireEvent, act, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Suspense } from 'react';
import userEvent from '@testing-library/user-event';
import { vi } from 'vitest';
import ArtifactPanel from './ArtifactPanel';
import type { Props as ArtifactPanelProps } from './ArtifactPanel';
import type { ArtifactVersion } from '@/types';
import * as artifactApiModule from '@/api/artifactApi';

vi.mock('@/api/artifactApi', () => ({
  fetchArtifactRawHtml: vi.fn(),
  fetchArtifactHtml: vi.fn().mockResolvedValue('<head></head><body>DASH</body>'),
  repairArtifact: vi.fn(),
}));

/** Renders ArtifactPanel wrapped in the QueryClientProvider + Suspense that ArtifactFrame
 *  (mounted internally via SuspenseLoader/ErrorBoundary) requires for useSuspenseQuery. */
function renderPanel(props: ArtifactPanelProps): ReturnType<typeof render> {
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(
    <QueryClientProvider client={queryClient}>
      <Suspense fallback={<div>loading</div>}>
        <ArtifactPanel {...props} />
      </Suspense>
    </QueryClientProvider>,
  );
}

/** Waits for ArtifactFrame's async-fetched iframe to mount. NEVER use screen.findByTitle for
 *  this — the header Select's selection-item div also carries a title="{artifact.title}"
 *  attribute (native truncation tooltip), so a title query can resolve to the wrong element
 *  before the iframe (which suspends on fetch) has actually mounted. */
async function findIframe(container: HTMLElement): Promise<HTMLIFrameElement> {
  return waitFor(() => {
    const iframe = container.querySelector('iframe');
    if (!iframe) throw new Error('iframe not yet mounted');
    return iframe as HTMLIFrameElement;
  });
}

const ARTIFACT = { artifactId: 'art-42', title: 'My Dashboard' };

// Titles follow the backend "Version N" convention to exercise the VERSION_TITLE_PREFIX label logic.
const makeVersions = (n: number): ArtifactVersion[] =>
  Array.from({ length: n }, (_, index) => ({
    artifactId: `art-${index + 1}`,
    title: `Version ${index + 1}`,
    version: index + 1,
  }));

// ── No artifact (empty state) ─────────────────────────────────

test('shows empty state when no artifact', () => {
  render(<ArtifactPanel artifact={null} />);
  expect(screen.getByText(/No artifact yet/i)).toBeInTheDocument();
  expect(screen.getByText(/Generated by eRD AI/i)).toBeInTheDocument();
});

test('empty state: refresh button is disabled', () => {
  render(<ArtifactPanel artifact={null} />);
  const refreshBtn = screen.getByTitle('重新整理儀表板');
  expect(refreshBtn).toBeDisabled();
});

test('empty state: no iframe rendered', () => {
  const { container } = render(<ArtifactPanel artifact={null} />);
  expect(container.querySelector('iframe')).toBeNull();
});

// ── With artifact ────────────────────────────────────────────

test('iframe has sandbox="allow-scripts" and srcdoc contains the fetched artifact html', async () => {
  const { container } = renderPanel({ artifact: ARTIFACT });
  const iframe = await findIframe(container);
  expect(iframe.getAttribute('sandbox')).toBe('allow-scripts');
  expect(iframe.getAttribute('srcdoc')).toContain('DASH');
});

test('displays artifact title in header via Select trigger', async () => {
  // ARTIFACT has title "My Dashboard" which does not start with "Version ".
  // labelRender falls back to showing the title as-is in the collapsed trigger.
  const { container } = renderPanel({ artifact: ARTIFACT });
  await findIframe(container);
  expect(screen.getByText('My Dashboard')).toBeInTheDocument();
});

test('refresh button is enabled when artifact is present and not streaming', async () => {
  const { container } = renderPanel({ artifact: ARTIFACT });
  await findIframe(container);
  const refreshBtn = screen.getByTitle('重新整理儀表板');
  expect(refreshBtn).not.toBeDisabled();
});

test('refreshButton_whileStreaming_disabled: refresh button is disabled when regenerating=true', async () => {
  const { container } = renderPanel({ artifact: ARTIFACT, regenerating: true });
  await findIframe(container);
  const refreshBtn = screen.getByTitle('重新整理儀表板');
  expect(refreshBtn).toBeDisabled();
});

test('refreshButton_click_remountsIframe: clicking refresh refetches with an incremented nonce and remounts the frame', async () => {
  const { container } = renderPanel({ artifact: ARTIFACT });

  const iframeBefore = await findIframe(container);
  expect(artifactApiModule.fetchArtifactHtml).toHaveBeenCalledWith('art-42', 0);

  await userEvent.click(screen.getByTitle('重新整理儀表板'));

  await waitFor(() => {
    expect(artifactApiModule.fetchArtifactHtml).toHaveBeenCalledWith('art-42', 1);
  });
  const iframeAfter = await findIframe(container);
  // Element replaced (unmounted + remounted) confirming React used a new key on nonce change.
  expect(iframeAfter).not.toBe(iframeBefore);
});

test('fullscreen button opens shell page url', async () => {
  const openSpy = vi.spyOn(window, 'open').mockReturnValue(null);
  renderPanel({ artifact: ARTIFACT });
  await userEvent.click(screen.getByTitle('Open the dashboard full-screen in a new tab'));
  expect(openSpy).toHaveBeenCalledWith('/?artifactView=art-42', '_blank', 'noopener,noreferrer');
  openSpy.mockRestore();
});

test('open fullscreen button is disabled when no artifact', () => {
  render(<ArtifactPanel artifact={null} />);
  const exportBtn = screen.getByTitle('Open the dashboard full-screen in a new tab');
  expect(exportBtn).toBeDisabled();
});

// ── Version dropdown ─────────────────────────────────────────

test('version dropdown renders options v1/v2/v3 when 3 versions provided', async () => {
  const versions = makeVersions(3);
  const activeArtifact = { artifactId: 'art-1', title: 'Version 1' };
  const { container } = renderPanel({ artifact: activeArtifact, artifacts: versions });
  await findIframe(container);
  // antd Select renders the current value label in the DOM via labelRender
  expect(screen.getByText('v1')).toBeInTheDocument();
});

test('version dropdown default value equals the passed artifact', async () => {
  const versions = makeVersions(3);
  // Active artifact is v2 — not latest, so trigger shows "v2" (no "Latest" suffix)
  const activeArtifact = { artifactId: 'art-2', title: 'Version 2' };
  const { container } = renderPanel({ artifact: activeArtifact, artifacts: versions });
  await findIframe(container);
  expect(screen.getByText('v2')).toBeInTheDocument();
});

test('onChange on version select triggers onSelectArtifact with correct artifact', async () => {
  const versions = makeVersions(3);
  const activeArtifact = { artifactId: 'art-1', title: 'Version 1' };
  const onSelectArtifact = vi.fn();

  const { container } = renderPanel({
    artifact: activeArtifact,
    artifacts: versions,
    onSelectArtifact,
  });

  // Open the Select dropdown via mousedown on the .ant-select container
  // (antd 6 uses .ant-select as the root; .ant-select-selector doesn't exist in v6)
  const selectEl = container.querySelector('.ant-select') as HTMLElement;
  fireEvent.mouseDown(selectEl);

  // Options are portal-rendered into document.body; optionRender shows the artifact title directly
  const v3Option = await screen.findByText('Version 3');
  fireEvent.click(v3Option);

  expect(onSelectArtifact).toHaveBeenCalledWith({ artifactId: 'art-3', title: 'Version 3' });
});

test('active artifact not in list adds dynamic vN+1 option', async () => {
  const versions = makeVersions(3);
  // Active artifact is a brand-new streaming one not yet in the persisted list.
  // Its title follows the "Version N" convention so labelRender derives the short label.
  const liveArtifact = { artifactId: 'art-live', title: 'Version 4' };
  const { container } = renderPanel({ artifact: liveArtifact, artifacts: versions });
  await findIframe(container);
  // Dynamic v4 is the latest → labelRender derives "v4 · Latest" from the title
  expect(screen.getByText('v4 · Latest')).toBeInTheDocument();
});

test('first-stream: artifacts=[] + artifact → dropdown shows v1 · Latest (N=0 early-return fix)', async () => {
  // Stream just produced the first artifact; the history query hasn't invalidated yet, so artifacts is still [].
  const liveArtifact = { artifactId: 'art-live', title: 'Version 1' };
  const { container } = renderPanel({ artifact: liveArtifact, artifacts: [] });
  await findIframe(container);
  // The single artifact is also the latest → labelRender derives "v1 · Latest" from the title.
  expect(screen.getByText('v1 · Latest')).toBeInTheDocument();
});

// ── Version label display (labelRender) ──────────────────────

test('selected latest version shows "v{N} · Latest" in the trigger', async () => {
  const versions = makeVersions(3);
  // art-3 has title "Version 3" and is the highest-version entry
  const activeArtifact = { artifactId: 'art-3', title: 'Version 3' };
  const { container } = renderPanel({ artifact: activeArtifact, artifacts: versions });
  await findIframe(container);
  // labelRender parses "Version 3" → "v3 · Latest"
  expect(screen.getByText('v3 · Latest')).toBeInTheDocument();
});

test('selected older version shows plain "v{n}" (no Latest suffix) in the trigger', async () => {
  const versions = makeVersions(3);
  // art-2 has title "Version 2" and is not the highest version
  const activeArtifact = { artifactId: 'art-2', title: 'Version 2' };
  const { container } = renderPanel({ artifact: activeArtifact, artifacts: versions });
  await findIframe(container);
  // labelRender parses "Version 2" → "v2"
  expect(screen.getByText('v2')).toBeInTheDocument();
  expect(screen.queryByText(/Latest/)).not.toBeInTheDocument();
});

test('labelRender_nonVersionPrefixTitle_showsTitleAsIs', async () => {
  // When the artifact title does not start with "Version ", labelRender returns it as-is.
  // This covers legacy or custom-named artifacts.
  const liveArtifact = { artifactId: 'art-custom', title: 'Sales Analysis Q2' };
  const { container } = renderPanel({ artifact: liveArtifact, artifacts: [] });
  await findIframe(container);
  expect(screen.getByText('Sales Analysis Q2')).toBeInTheDocument();
});

// ── Version dropdown options (optionRender + sort order) ──────

test('dropdown options show "Version N" labels sorted newest to oldest', async () => {
  const versions = makeVersions(3);
  const activeArtifact = { artifactId: 'art-1', title: 'Dashboard 1' };
  const { container } = renderPanel({ artifact: activeArtifact, artifacts: versions });

  const selectEl = container.querySelector('.ant-select') as HTMLElement;
  fireEvent.mouseDown(selectEl);

  // Wait for the dropdown to appear
  const version3El = await screen.findByText('Version 3');
  const version2El = screen.getByText('Version 2');
  const version1El = screen.getByText('Version 1');

  // Verify DOM order: v3 before v2 before v1 (Node.DOCUMENT_POSITION_FOLLOWING = 4)
  expect(
    version3El.compareDocumentPosition(version2El) & Node.DOCUMENT_POSITION_FOLLOWING,
  ).toBeTruthy();
  expect(
    version2El.compareDocumentPosition(version1El) & Node.DOCUMENT_POSITION_FOLLOWING,
  ).toBeTruthy();
});

test('dropdown latest option shows "Latest" badge; non-latest options do not', async () => {
  const versions = makeVersions(3);
  const activeArtifact = { artifactId: 'art-1', title: 'Dashboard 1' };
  const { container } = renderPanel({ artifact: activeArtifact, artifacts: versions });

  const selectEl = container.querySelector('.ant-select') as HTMLElement;
  fireEvent.mouseDown(selectEl);

  await screen.findByText('Version 3');

  // Exactly one "Latest" badge should appear (for version 3)
  const latestBadges = screen.queryAllByText('Latest');
  expect(latestBadges).toHaveLength(1);
});

// ── Runtime error forwarding ──────────────────────────────────

describe('runtime error forwarding', () => {
  beforeEach(() => {
    vi.mocked(artifactApiModule.repairArtifact).mockClear();
  });

  test('valid erd-artifact-error message calls onRuntimeErrors with artifactId and errors', async () => {
    const onRuntimeErrors = vi.fn();
    const { container } = renderPanel({ artifact: ARTIFACT, onRuntimeErrors });
    const iframe = await findIframe(container);
    const event = new MessageEvent('message', {
      data: {
        type: 'erd-artifact-error',
        errors: [{ message: 'ReferenceError: foo', line: 1, col: 0 }],
      },
      source: iframe.contentWindow,
    });
    await act(async () => {
      window.dispatchEvent(event);
    });
    expect(onRuntimeErrors).toHaveBeenCalledWith('art-42', [
      { message: 'ReferenceError: foo', line: 1, col: 0 },
    ]);
    expect(artifactApiModule.repairArtifact).not.toHaveBeenCalled();
  });

  test('message with wrong type does not call onRuntimeErrors', async () => {
    const onRuntimeErrors = vi.fn();
    const { container } = renderPanel({ artifact: ARTIFACT, onRuntimeErrors });
    await findIframe(container);
    const event = new MessageEvent('message', {
      data: { type: 'other-event', errors: [] },
    });
    await act(async () => {
      window.dispatchEvent(event);
    });
    expect(onRuntimeErrors).not.toHaveBeenCalled();
  });

  test('message from wrong source does not call onRuntimeErrors', async () => {
    const onRuntimeErrors = vi.fn();
    const { container } = renderPanel({ artifact: ARTIFACT, onRuntimeErrors });
    await findIframe(container);
    const event = new MessageEvent('message', {
      data: {
        type: 'erd-artifact-error',
        errors: [{ message: 'ReferenceError: foo', line: 1, col: 0 }],
      },
      // source intentionally omitted → not from the iframe
    });
    await act(async () => {
      window.dispatchEvent(event);
    });
    expect(onRuntimeErrors).not.toHaveBeenCalled();
  });

  test('reloadNonce=2 → frame fetch is called with nonce=2', async () => {
    const { container } = renderPanel({ artifact: ARTIFACT, reloadNonce: 2 });
    await findIframe(container);
    expect(artifactApiModule.fetchArtifactHtml).toHaveBeenCalledWith('art-42', 2);
  });

  test('reloadNonce=0 (default) → frame fetch is called with nonce=0', async () => {
    const { container } = renderPanel({ artifact: ARTIFACT });
    await findIframe(container);
    expect(artifactApiModule.fetchArtifactHtml).toHaveBeenCalledWith('art-42', 0);
  });
});
