"""主 agent 的 AgentMiddleware——deepagents 只把自訂 middleware 掛到主 agent，
子代理的 middleware 由各自的 subagent spec 帶，故此處的鎖不會與 `task` 工具互鎖。"""

import asyncio
import re
from collections.abc import Awaitable, Callable

from langchain.agents.middleware.types import AgentMiddleware, ModelRequest
from langchain_core.messages import AIMessage, SystemMessage, ToolMessage
from langgraph.prebuilt.tool_node import ToolCallRequest
from langgraph.types import Command

from app.engine.results import format_wiring_manifest, load_all_results
from app.engine.workspace import SessionWorkspace

ToolCallHandler = Callable[[ToolCallRequest], Awaitable[ToolMessage | Command]]
ModelCallHandler = Callable[[ModelRequest], Awaitable[AIMessage]]


class SerializedToolCallsMiddleware(AgentMiddleware):
    """同一則 AI message 的多個 tool call 一次只跑一個。ToolNode 預設用 `asyncio.gather`
    併發送出 tool call，而 deepagents 的 write_file/edit_file 是無鎖讀改寫——併發打同一
    檔案會靜默互相覆蓋。鎖的範圍是一次 `/chat`（per-request build_agent），不跨 request。
    """

    def __init__(self) -> None:
        super().__init__()
        self._tool_call_lock = asyncio.Lock()

    async def awrap_tool_call(
        self, request: ToolCallRequest, handler: ToolCallHandler
    ) -> ToolMessage | Command:
        async with self._tool_call_lock:
            return await handler(request)


class WiringManifestMiddleware(AgentMiddleware):
    """每次 model call 都把目前 qN 清單、intent、欄位附在 system message 後面。每次呼叫
    重建而非每輪一次:同一輪內常見「先查詢後寫 dashboard」，turn 開始時 results 還不存在，
    turn-start 注入對此情境無效。
    """

    def __init__(self, workspace: SessionWorkspace) -> None:
        super().__init__()
        self._workspace = workspace

    async def awrap_model_call(self, request: ModelRequest, handler: ModelCallHandler) -> AIMessage:
        manifest_text = format_wiring_manifest(load_all_results(self._workspace))
        if not manifest_text:
            return await handler(request)
        existing_text = request.system_message.content if request.system_message else ""
        return await handler(
            request.override(system_message=SystemMessage(f"{existing_text}\n\n{manifest_text}"))
        )


_GATED_FILE_NAME = "dashboard.html"

# renderer_subagent.py 從這裡 import 並 re-export——避免它與 middleware.py 互相 import
# 造成循環(renderer_subagent 已經單向依賴 middleware 的 WiringManifestMiddleware)。
RENDERER_SUBAGENT_NAME = "dashboard-renderer"

HARVEST_CONFIRMATION_PREFIX = "dashboard.html updated"


def _normalized_workspace_path(file_path: str) -> str:
    """把 virtual_mode 的絕對寫法 `/a/b` 與相對寫法 `a/b` 收斂成同一種字串,好做比對。"""
    return file_path.strip().lstrip("/")


class DashboardDelegationGateMiddleware(AgentMiddleware):
    """主 agent 直寫 dashboard.html 一律擋下(write_file 與 edit_file 都擋)——dashboard 只由
    dashboard-renderer subagent 生成、由 harvest middleware 寫檔。notes.md 等其他檔不受限。"""

    async def awrap_tool_call(
        self, request: ToolCallRequest, handler: ToolCallHandler
    ) -> ToolMessage | Command:
        tool_call = request.tool_call
        if tool_call.get("name") in ("write_file", "edit_file"):
            file_path = _normalized_workspace_path(
                str(tool_call.get("args", {}).get("file_path", ""))
            )
            if file_path == _GATED_FILE_NAME:
                return ToolMessage(
                    content=(
                        "Blocked: dashboard.html is generated by the dashboard-renderer "
                        "subagent, never written directly. First record the conclusions to "
                        "visualize in notes.md, then call the task tool with "
                        f"subagent_type='{RENDERER_SUBAGENT_NAME}' and a one-two sentence "
                        "description of what to build or change."
                    ),
                    tool_call_id=tool_call["id"],
                    status="error",
                )
        return await handler(request)


_HTML_FENCE_PATTERN = re.compile(r"```html\s*\n(.*?)(?:\n```|\Z)", re.IGNORECASE | re.DOTALL)
_HTML_START_PATTERN = re.compile(r"<!doctype|<html", re.IGNORECASE)
_HTML_END_PATTERN = re.compile(r"</html>", re.IGNORECASE)


def _extract_html_document(reply_text: str) -> str | None:
    """從回覆文字撈完整 HTML 文件,容忍開場白/收尾雜訊(實測 round-1 樣態):優先抓任意位置的
    ```html fence(無收尾 fence 就吃到字串末),否則抓第一個 <!doctype/<html 起點;截到最後一個
    </html> 為止,無此收尾字串視為殘品,寧可退貨重試也不收半成品。"""
    fence_match = _HTML_FENCE_PATTERN.search(reply_text)
    if fence_match:
        candidate = fence_match.group(1)
    else:
        start_match = _HTML_START_PATTERN.search(reply_text)
        if start_match is None:
            return None
        candidate = reply_text[start_match.start() :]
    end_matches = list(_HTML_END_PATTERN.finditer(candidate))
    if not end_matches:
        return None
    return candidate[: end_matches[-1].end()].strip()


class RendererDeliveryChannelMiddleware(AgentMiddleware):
    """renderer 的 write_file 習性收割:目標是 dashboard.html(任何目錄)且內容為完整 HTML 就
    由程式碼直接寫進 workspace(成功+引導收尾);其他寫檔一律轉向「把 HTML 當回覆輸出」。"""

    def __init__(self, workspace: SessionWorkspace) -> None:
        super().__init__()
        self._workspace = workspace

    async def awrap_tool_call(
        self, request: ToolCallRequest, handler: ToolCallHandler
    ) -> ToolMessage | Command:
        tool_call = request.tool_call
        tool_name = tool_call.get("name")
        if tool_name not in ("write_file", "edit_file"):
            return await handler(request)
        arguments = tool_call.get("args", {})
        file_path = str(arguments.get("file_path", ""))
        if tool_name == "write_file" and file_path.rstrip("/").endswith("dashboard.html"):
            html_candidate = _extract_html_document(str(arguments.get("content", "")))
            if html_candidate is not None:
                self._workspace.dashboard_path.write_text(html_candidate, encoding="utf-8")
                return ToolMessage(
                    content=(
                        "dashboard.html saved. Now reply with ONE short sentence to finish -- "
                        "do NOT paste the HTML and do NOT call any more tools."
                    ),
                    tool_call_id=tool_call["id"],
                    status="success",
                )
        return ToolMessage(
            content=(
                "File writes are not available here. Deliver the dashboard by outputting the "
                "COMPLETE HTML document directly as your reply text, starting at <!DOCTYPE html> "
                "and ending at </html>. Do not call file tools again."
            ),
            tool_call_id=tool_call["id"],
            status="error",
        )


class DashboardRenderHarvestMiddleware(AgentMiddleware):
    """攔 dashboard-renderer 的 task 回傳:完整 HTML 由這裡(程式碼,非模型)寫入
    dashboard.html,ToolMessage 換成短確認,不回灌主 context;非 HTML 回覆改 error 讓主 agent 重試不寫檔。
    回覆通道優先(最新版為準);若回覆抽不出 HTML 但 handler 執行期間 dashboard.html 已被
    RendererDeliveryChannelMiddleware 寫入(write_file 通道),仍視為送達成功。"""

    def __init__(self, workspace: SessionWorkspace) -> None:
        super().__init__()
        self._workspace = workspace

    async def awrap_tool_call(
        self, request: ToolCallRequest, handler: ToolCallHandler
    ) -> ToolMessage | Command:
        tool_call = request.tool_call
        is_renderer_task = (
            tool_call.get("name") == "task"
            and tool_call.get("args", {}).get("subagent_type") == RENDERER_SUBAGENT_NAME
        )
        dashboard_mtime_before = self._dashboard_mtime() if is_renderer_task else None
        result = await handler(request)
        if not is_renderer_task:
            return result
        reply_message = self._extract_tool_message(result)
        if reply_message is None:
            return result
        html_candidate = _extract_html_document(str(reply_message.content))
        if html_candidate is not None:
            self._workspace.dashboard_path.write_text(html_candidate, encoding="utf-8")
            delivered_chars = len(html_candidate)
        elif self._dashboard_mtime() != dashboard_mtime_before:
            delivered_chars = len(self._workspace.dashboard_path.read_text(encoding="utf-8"))
        else:
            return self._replace_message(
                result,
                reply_message,
                content=(
                    "Renderer reply was not a complete HTML document (must start at "
                    "<!DOCTYPE html>). Nothing was written. Add the missing context to "
                    "notes.md if needed, then call task again with "
                    f"subagent_type='{RENDERER_SUBAGENT_NAME}'."
                ),
                status="error",
            )
        confirmation = (
            f"{HARVEST_CONFIRMATION_PREFIX} ({delivered_chars} chars). Do NOT paste HTML "
            "in your reply; give the user a short Traditional-Chinese summary of what the "
            "dashboard now shows."
        )
        return self._replace_message(result, reply_message, content=confirmation, status="success")

    def _dashboard_mtime(self) -> float | None:
        if not self._workspace.dashboard_path.exists():
            return None
        return self._workspace.dashboard_path.stat().st_mtime

    def _extract_tool_message(self, result: ToolMessage | Command) -> ToolMessage | None:
        if isinstance(result, ToolMessage):
            return result
        if isinstance(result, Command):
            messages = (result.update or {}).get("messages") or []
            for message in messages:
                if isinstance(message, ToolMessage):
                    return message
        return None

    def _replace_message(
        self,
        result: ToolMessage | Command,
        original: ToolMessage,
        *,
        content: str,
        status: str,
    ) -> ToolMessage | Command:
        replacement = ToolMessage(
            content=content, tool_call_id=original.tool_call_id, status=status
        )
        if isinstance(result, ToolMessage):
            return replacement
        replaced_messages = [
            replacement if message is original else message
            for message in (result.update or {}).get("messages", [])
        ]
        return Command(update={**result.update, "messages": replaced_messages})
